<?php

/**
 * This is the model base class for the table "education".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Education".
 *
 * Columns in table "education" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $degree
 *
 */
abstract class BaseEducation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'education';
	}

	public static function representingColumn() {
		return 'degree';
	}

	public function rules() {
		return array(
			array('user_id, degree', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('degree', 'length', 'max'=>6),
			array('id, user_id, degree', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'degree' => Yii::t('app', 'Degree'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('degree', $this->degree, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}